ac_gacmr_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import mainapp.views as mainapp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", mainapp.index, name="index"),
    path("reestr/", mainapp.reestr, name="reestr"),
    path("pdn-politics/", mainapp.pdn_politics, name="pdn-politics"),
    path("doc/", mainapp.doc, name="doc"),
    path("details/<slug:content>/<slug:pk>", mainapp.details, name="details"),
    path("news_two/", mainapp.news_two, name="news_two"),
    path("all_news/", mainapp.all_news, name="all_news"),
    path("political/", mainapp.political, name="political"),
    path("ocenka_details/", mainapp.ocenka_details, name="ocenka_details"),
    path("profstandarti/", mainapp.profstandarti, name="profstandarti"),
    path("center/", mainapp.center, name="center"),
    path("detailview/<slug:content>/<slug:pk>", mainapp.details, name="detailview"),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("accept_order/", mainapp.accept_order, name="accept_order"),
    path("captcha/", include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ac_ufa_site/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', mainapp.index, name='index'),
   path('reestr/', mainapp.reestr, name='reestr'),
   path('doc/', mainapp.doc, name='doc'),
   path('details/<slug:content>/<slug:pk>', mainapp.details, name='details'),
   path('news_two/', mainapp.news_two, name='news_two'),
   path('all_news/', mainapp.all_news, name='all_news'),
   path('political/', mainapp.political, name='political'),
   path('ocenka_details/', mainapp.ocenka_details, name='ocenka_details'),
   path('profstandarti/', mainapp.profstandarti, name='profstandarti'),
   path('center/', mainapp.center, name='center'),
   path(
        'detailview/<slug:content>/<slug:pk>',
        mainapp.details,
        name='detailview'),
   path('ckeditor/', include('ckeditor_uploader.urls')),
   path('accept_order/', mainapp.accept_order, name="accept_order"),
   path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
"""
File: models.py
Email: yourname@email.com
Description: models to site project
"""
import os

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
# using this as a store for weld orgs:
from picklefield.fields import PickledObjectField
from stdimage import StdImageField

# from django_resized import ResizedImageField


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Category(models.Model):
    """category model class"""

    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class ContentMixin(models.Model):
    """base class for Post, Article and Documents"""

    number = models.PositiveSmallIntegerField(default=0)
    title = models.CharField("Название", max_length=200)
    url_code = models.CharField(
        "Код ссылки", max_length=30, blank=True, default="НЕ УКАЗАН"
    )

    short_description = models.CharField("Краткое описание", max_length=200, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name="Тэги")
    published_date = models.DateTimeField("Дата публикации", blank=True, null=True)
    created_date = models.DateTimeField("Дата создания", default=timezone.now)
    text = RichTextUploadingField(verbose_name="Текст")
    author = models.ForeignKey(
        "auth.User", verbose_name="Автор", on_delete=models.CASCADE
    )
    publish_on_main_page = models.BooleanField(
        verbose_name="Опубликовать на главной", default=False
    )

    class Meta:
        abstract = True


class Post(ContentMixin):
    """child of contentmixin"""

    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.CASCADE
    )
    publish_on_news_page = models.BooleanField(
        verbose_name="Опубликовать в ленте новостей", default=False
    )
    publish_in_basement = models.BooleanField(
        "Опубликовать в подвале на главной", default=False
    )

    class Meta:
        ordering = ["created_date"]
        get_latest_by = ["created_date"]
        verbose_name = "Страница"
        verbose_name_plural = "Страницы"

    def get_absolute_url(self):
        return reverse("detailview", kwargs={"content": "post", "pk": self.pk})

    def publish(self):
        """unused function"""
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Article(ContentMixin):
    """child of ContentMixin"""

    class Meta:
        ordering = ["created_date"]
        get_latest_by = ["created_date"]
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    def publish(self):
        """unused, left for future"""
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Document(models.Model):
    title = models.CharField("Название", max_length=500)
    url_code = models.CharField(
        "Код ссылки", max_length=30, blank=True, default="НЕ УКАЗАН"
    )
    document = models.FileField(
        verbose_name="Документ",
        upload_to="documents/",
        validators=[
            FileExtensionValidator(
                allowed_extensions=["pdf", "docx", "doc", "jpg", "jpeg"],
                message="Неправильный тип файла, используйте\
                                        PDF, DOCX, DOC, JPG, JPEG",
            )
        ],
    )
    preview = models.FileField(
        null=True,
        blank=True,
        upload_to="documents/",
    )
    uploaded_at = models.DateTimeField(verbose_name="Загружен", default=timezone.now)
    tags = models.ManyToManyField(Tag, verbose_name="Тэги", blank=True)
    created_date = models.DateTimeField(
        default=timezone.now, verbose_name="Дата создания"
    )
    post = models.ForeignKey(
        Post,
        verbose_name="Страница",
        blank=True,
        default="",
        on_delete=models.SET_NULL,
        null=True,
    )
    publish_on_main_page = models.BooleanField(
        verbose_name="Опубиковать на главной", default=False
    )

    class Meta:
        verbose_name = "Документ"
        verbose_name_plural = "Документы"

    def __str__(self):
        return self.title

    def extension(self):
        name, extension = os.path.splitext(self.document.name)
        return extension


def upload_to(instance, filename):
    """left for future, unused function"""
    filename_base, filename_ext = os.path.splitext(filename)
    return "upload/{post_pk}/{filename}{extension}".format(
        post_pk=instance.pk,
        filename=slugify(filename_base),
        extension=filename_ext.lower(),
    )


def get_image_filename():
    """unused function, left for future"""
    return "image_{}".format(slugify(timezone.now()))


class PostPhoto(models.Model):
    """model to load photos to content page"""

    post = models.ForeignKey(
        Post,
        verbose_name="новость",
        related_name="images",
        on_delete=models.SET_NULL,
        null=True,
    )
    image = models.ImageField("изображение", upload_to="upload/")
    title = models.CharField(
        "название", max_length=64, blank=True, default=get_image_filename
    )
    position = models.PositiveIntegerField("Позиция", default=0)

    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фотографии"
        ordering = ["position"]

    def __str__(self):
        return "{} - {}".format(self.post, self.image)


class CenterPhoto(models.Model):
    number = models.PositiveSmallIntegerField(default=0)
    title = models.CharField(max_length=50)
    image = StdImageField(
        upload_to="center_photos/",
        variations={
            "thumb": {"width": 400, "height": 200},
            "full": {"width": 800, "height": 400},
        },
    )


class Message(models.Model):
    """this is the class to use within adapter patter realization"""

    STATUS_LIST = (
        (0, "new"),
        (1, "registered"),
        (2, "added_to_sending_queue"),
        (3, "notify_sent"),
    )
    title = models.CharField("Заголовок", max_length=64, blank=True)
    typeof = models.CharField("Тип сообщения", max_length=64, blank=True)
    params = models.CharField("Параметры сообщения", max_length=512, blank=True)
    sender_email = models.EmailField(
        "Адрес электронной почты", max_length=64, blank=True
    )
    sender_phone = models.CharField("Телефон", max_length=64, blank=True)
    created_date = models.DateTimeField("Дата получения", default=timezone.now)
    status = models.IntegerField("Статус", default=0, choices=STATUS_LIST)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return self.title

    def set_status(self, status_code):
        # if status_code in STATUS_LIST:
        self.status = status_code


class Contact(models.Model):
    title = models.CharField("Название контакта", max_length=64, blank=False)
    description = models.CharField("Описание", max_length=200, blank=False)
    email = models.EmailField("Адрес электронной почты", max_length=64, blank=False)
    phone = models.CharField("Телефон", max_length=64, blank=False)
    number = models.SmallIntegerField("Порядок вывода на сайт", default=0)

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

    def __str__(self):
        return self.title


class Staff(models.Model):
    photo = models.ImageField("Фотография", blank=True)
    name = models.CharField("ФИО", max_length=120, blank=False)
    job = models.CharField("Должность", max_length=120, blank=False)
    experience = models.CharField("Опыт работы", max_length=500, blank=True)
    priority = models.SmallIntegerField("Приоритет", default=0)

    class Meta:
        verbose_name = "Сотрудник"
        verbose_name_plural = "Сотрудники"

    def __str__(self):
        return "{} - {}".format(self.name, self.job)


class Menu(models.Model):
    """linking main page UI elements with its description"""

    url_code = models.CharField("Код ссылки", max_length=30)
    title = models.CharField("Заголовок ссылки", max_length=60)
    url = models.CharField("Адрес ссылки", max_length=200, default="НЕТ")

    class Meta:
        verbose_name = "Ссылка"
        verbose_name_plural = "Ссылки"

    def __str__(self):
        return self.title


class Registry(models.Model):
    """this is the class to load external registry records"""

    STATUS_LIST = ((0, "new"), (1, "published"))
    title = models.CharField("Название", max_length=64, blank=True)
    org = models.CharField("Организация", max_length=120, blank=True)
    typeof = models.CharField("Тип", max_length=64, blank=True)
    params = models.CharField("Параметры", max_length=999, blank=True)
    created_date = models.DateField("Дата получения", blank=True)
    status = models.IntegerField("Статус", default=0, choices=STATUS_LIST)

    class Meta:
        verbose_name = "Запись реестра"
        verbose_name_plural = "Записи реестра"

    def __str__(self):
        return self.title


class WeldData(models.Model):
    """database agnostic storage for weld-data"""

    title = models.CharField("Название", blank=True, max_length=100)
    uid = models.IntegerField("UID", unique=True, blank=True)
    args = PickledObjectField()

    class Meta:
        abstract = True


class Profstandard(models.Model):

mainapp/forms.py
from django import forms
from django.core.validators import FileExtensionValidator, validate_email
import os
from captcha.fields import CaptchaField

from .models import Post, Article, Document, OrderService


class ContentForm(forms.ModelForm):
    """form to use with fabric in news-view"""

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        fieldset = {
            'post_form_fields': ('title', 'tags', 'category', 'author', 'text',
                                 'created_date', 'published_date'),
            'article_form_fields': ('title', 'tags', 'author', 'text',
                                    'created_date', 'published_date'),
            'document_form_fields': ('title', 'document', 'tags',
                                     'created_date', 'uploaded_at')
        }


class PostForm(ContentForm):

    class Meta(ContentForm.Meta):
        model = Post
        fields = ContentForm.Meta.fieldset['post_form_fields']


class ArticleForm(ContentForm):

    class Meta(ContentForm.Meta):
        model = Article
        fields = ContentForm.Meta.fieldset['article_form_fields']


class DocumentForm(ContentForm):
    ALOWED_TYPES = ['jpg', 'jpeg', 'doc', 'docx', 'pdf', 'xls', 'xlsx']

    class Meta(ContentForm.Meta):
        model = Document
        fields = ContentForm.Meta.fieldset['document_form_fields']


class SendMessageForm(forms.Form):
    name = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={'class': 'modal__form_input'}))
    phone = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'class': 'modal__form_input'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'modal__form_input'}))
    params = forms.CharField(required=False, max_length=128)
    comment = forms.CharField(
        required=False, max_length=256, widget=forms.Textarea(
            attrs={'class': 'modal__form_textarea'}))
    pdata = forms.BooleanField(
        initial=True, required=True, widget=forms.CheckboxInput(
            attrs={'class': 'checkmark'}))


class SubscribeForm(forms.Form):
    email = forms.EmailField(
        required=True, widget=forms.EmailInput(
            attrs={'class': 'main-footer__subscribe-email--input',
                   'placeholder': 'Введите e-mail'}))


class AskQuestionForm(forms.Form):
    name = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={'class': 'modal__form_input'}))
    phone = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'class': 'modal__form_input'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'modal__form_input'}))
    comment = forms.CharField(
        required=False, max_length=256, widget=forms.Textarea(
            attrs={'class': 'modal__form_textarea'}))
    pdata = forms.BooleanField(
        error_messages={
            'required': 'Вы должны принять условия обработки \
            персональных данных в соответствии с 152-ФЗ'},
        initial=True, required=True, widget=forms.CheckboxInput(
            attrs={'class': 'checkmark'}))


class SearchRegistryForm(forms.Form):
    fio = forms.CharField(max_length=64, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    work_place = forms.CharField(max_length=64, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    # def clean(self):
    #     document = self.cleaned_data.get('document', None)
    #     if not document:
    #         raise forms.ValidationError('Missing document file')
    #     try:
    #         extension = os.path.splitext(document.name)[1][1:].lower()
    #         if extension in self.ALOWED_TYPES:
    #             return document
    #         else:
    #             raise forms.ValidationError('File types is not allowed')
    #     except Exception as e:
    #         raise forms.ValidationError('Can not identify file type')

class OrderForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = OrderService
        fields = ['name', 'phone', 'compound']
        widgets = {
                'name': forms.TextInput({
                'placeholder': "Ваше имя",
                'class': 'form-control form-control-sm',
                }),
                'phone': forms.TextInput({
                    'placeholder': '',
                    'class': 'form-control form-control-sm',
                    'type': 'text',
                }),
                # <input type="text" class="form-control form-control-sm" placeholder=""  type="text" id="phone2" required="">
            }

#class Test

mainapp/templates/mainapp/includes/detail_service.html
{% load static %}
{% load link_holders %}
<div id="trueModal{{ publ.post.pk }}"
     style="display: none;
            max-width: 1200px">
    <div class="row align-items-center">
        <div class="col-xl-12">
            <div class="caption_in_modal_window">
                <div data-fancybox-close="">
                    <img src="{% static '/img/close__icon-01.png' %}"
                         class="close_modal float-right mt-1"
                         title="Закрыть"
                         alt="">
                </div>
                {{ publ.post.title }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="text_in_a_modal_window">{{ publ.post.text|safe }}</div>
            <div class="line_modal_info"></div>
            {% comment %}
                        <button class="request">
                                <a href="" data-toggle="modal" data-target="#modal-statement" class="request_button">Подать
                                        заявку</a>
                        </button>  
            {% endcomment %}
        </div>
    </div>
</div>

mainapp/templates/mainapp/includes/gallery.html
{% load static %}
{% if center_photos %}
    <div class="box_background">
        <div class="container">
            <div class="row">
                <div class="col-xl-1">
                    <div class="left_line_headline"></div>
                </div>
                <div class="col-xl-6">
                    <p class="headline_text">Фотографии нашего центра</p>
                    <p class="subtitle">123</p>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12">
                    <div class="owl-carousel-gallery owl-theme">
                        {% for photo in center_photos %}
                            <a href="{{ photo.image.full.url }}" data-fancybox="images">
                                <img src="{{ photo.image.thumb.url }}" class="img-fluid" />
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

mainapp/templates/mainapp/includes/modal-window.html
{% load static %}
<div class="modal fade"
     id="modal-statement"
     tabindex="-1"
     role="dialog"
     aria-labelledby=""
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="">Обратная связь</h5>
                <div class="row">
                    <div class="col col-sm-10 col-xl-6">
                        <p class="modal__title__small__text">
                            Введите свои контактные данные, выберите одну или
                            несколько заявок  для прохождения аттестации, и наш специалист свяжется с вами в ближайшее время.
                        </p>
                    </div>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        <img src="{% static 'img/close2.png' %}" title="Закрыть окно" alt="">
                    </span>
                </button>
            </div>
            <form id="order_form">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="id_name" class="col-form-label col-form-label-sm">Имя</label>
                                {% comment %} <input type="text" class="form-control form-control-sm" id="" required="">
                                {% endcomment %}
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="" class="col-form-label col-form-label-sm">Номер телефона</label>
                                {% comment %} <input type="text"
        class="form-control form-control-sm"
        placeholder=""
        type="text"
        id="phone"
        required=""> {% endcomment %}
                                {{ form.phone }}
                            </div>
                        </div>
                        <div class="col-xl-9">
                            <div class="form-group ">
                                <label for="" class="col-form-label col-form-label-sm">Вид заявки(-ок)</label>
                                <div class="choose__item">
                                    <ul class="items">
                                        <li data-selected="0" data-guid="3" data-order="attsvsp">
                                            Аттестация персонала
                                            сварочного производства
                                        </li>
                                        <li data-selected="0" data-guid="3" data-order="attsm">
                                            Аттестация сварочных
                                            материалов
                                        </li>
                                        <li data-selected="0" data-guid="3" data-order="attso">
                                            Аттестация сварочного
                                            оборудования
                                        </li>
                                        <li data-selected="0" data-guid="3" data-order="attst">
                                            Аттестация сварочных
                                            технологий
                                        </li>
                                        <li data-selected="0" data-guid="3" data-order="attlab">
                                            Лаборатория
                                            неразрушающего контроля
                                        </li>
                                        <li data-selected="0" data-guid="3" data-order="ocenka">Оценка квалификации в области сварки и контроля</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="custom-control-checkbox custom-checkbox d-inline-block">
                        <input type="checkbox"
                               class="custom-control-input"
                               id="soglasie"
                               required="">
                        <label class="custom-control-label" for="soglasie">
                            <small>Я даю <a id="soglasie" href="#">согласие на обработку персональных данных</small>
                        </label>
                        <div id="order_captcha_check">
                            {{ form.captcha }}
                            <div id="order_captcha_message"></div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="order_service_button"
                            type="submit"
                            class="button__to__send_zayavka__formmodal d-inline-block">
                        Отправить
                        заявку
                    </button>
                </div>
            </form>
            {% comment %} <form>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="" class="col-form-label col-form-label-sm">Ваше имя</label>
                                <input type="text" class="form-control form-control-sm" id="" required="">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="" class="col-form-label col-form-label-sm">Номер телефона</label>
                                <input type="text" class="form-control form-control-sm" placeholder="" type="text" id="phone" required="">
                            </div>
                        </div>
                        <div class="col-xl-9">
                            <div class="form-group ">
                                <label for="" class="col-form-label col-form-label-sm">Вид заявки(-ок)</label>
                                <div class="choose__item">
                                    <ul class="items">
                                        <li data-selected="0" data-guid="3">Аттестация сварочных материалов</li>
                                        <li data-selected="0" data-guid="3">Аттестация сварочного оборудования</li>
                                        <li data-selected="0" data-guid="3">Аттестация сварочных технологий</li>
                                        <li data-selected="0" data-guid="2">Аттестация специалистов неразрушающего контроля</li>
                                        <li data-selected="0" data-guid="1">Аттестация лабораторий неразрушающего контроля</li>
                                        <li data-selected="0" data-guid="1">Аттестация специалистов сварочного производства</li>
                                        <li data-selected="0" data-guid="1">Независимая оценка квалификации</li>
                                        <li data-selected="0" data-guid="1">Услуги неразрушающему контролю</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-xl-6">
                            <form method="post" class="file-uploader" action="" enctype="multipart/form-data">
                                <div class="file-uploader__message-area">
                                    <p>Выбрать файл</p>
                                </div>
                                <div class="file-chooser">
                                    <input class="file-chooser__input" type="file">
                                </div>
                                <!-- <input class="file-uploader__submit-button" type="submit" value="Загрузить"> -->
                            </form>
                        </div>
                    </div>
                    <div class="custom-control-checkbox custom-checkbox d-inline-block">
                        <input type="checkbox" class="custom-control-input" id="soglasie" required="">
                        <label class="custom-control-label" for="soglasie"><small>Я даю <a href="#">согласие на
                                    обработку персональных данных</a></small></label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="button__to__send_zayavka__formmodal d-inline-block">Отправить заявку</button>

                </div>
            </form> {% endcomment %}
        </div>
    </div>
</div>
<!-- End Набор в группу аттестации -->
<!-- Модальное окно - Задать вопрос -->
<div class="modal fade"
     id="modal-question"
     tabindex="-1"
     role="dialog"
     aria-labelledby=""
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header-feedback">
                <div class="modal-header">
                    <h5 class="modal-title" id="">Задать вопрос</h5>
                    <div class="row">
                        <div class="col col-sm-10 col-xl-8">
                            <p class="modal__title__small__text">
                                Есть вопросы по аттестации?
                                <br>
                                Оставляйте заявку на вопрос, и наш специалист ответит в ближайшее время.
                            </p>
                        </div>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">
                            <img src="{% static 'img/close2.png' %}" alt="">
                        </span>
                    </button>
                </div>
            </div>
            <form>
                <div class="modal-body px-3 px-sm-5">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="" class="col-form-label col-form-label-sm">Имя</label>
                                <input type="text" class="form-control form-control-sm" id="" required="">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="" class="col-form-label col-form-label-sm">Номер телефона</label>
                                <input type="text"
                                       class="form-control form-control-sm"
                                       placeholder=""
                                       type="text"
                                       id="phone2"
                                       required="">
                            </div>
                        </div>
                    </div>
                    <div class="custom-control-checkbox custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="sogl" required="">
                        <label class="custom-control-label" for="sogl">
                            <small>Я даю <a href="#" target="_blank">согласие
                            на обработку персональных данных</a></small>
                        </label>
                    </div>
                </div>
                <div class="modal-footer pb-5 px-3 px-sm-5">
                    <button type="submit" class="button__to__send_zayavka__formmodal">Отправить</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Задать вопрос -->